/// Chat types for multi-turn conversation management
///
/// Provides [ChatMessage], [ChatRole], and [SystemPromptPreset] types
/// used by [ChatSession] to manage conversation history.
library;

/// Role of a message in a conversation
enum ChatRole {
  /// Message from the user
  user,

  /// Response from the assistant/model
  assistant,

  /// System instruction (set at session creation)
  system,

  /// Summarized conversation history (generated by context overflow handling)
  summary,

  /// Tool invocation request from the model
  toolCall,

  /// Tool execution result provided by the developer
  toolResult,
}

/// A single message in a conversation
class ChatMessage {
  /// Role of the message sender
  final ChatRole role;

  /// Text content of the message
  final String content;

  /// When this message was created
  final DateTime timestamp;

  /// Create a new chat message
  const ChatMessage({
    required this.role,
    required this.content,
    required this.timestamp,
  });

  @override
  String toString() =>
      'ChatMessage(${role.name}: "${content.length > 50 ? '${content.substring(0, 50)}...' : content}")';
}

/// Built-in system prompt presets for common use cases
///
/// Use these with [ChatSession] for quick setup:
/// ```dart
/// final session = ChatSession(
///   edgeVeda: edgeVeda,
///   preset: SystemPromptPreset.assistant,
/// );
/// ```
enum SystemPromptPreset {
  /// General-purpose helpful assistant
  assistant('You are a helpful assistant. Provide clear, concise answers.'),

  /// Coding-focused assistant with code examples
  coder(
      'You are a coding assistant. Provide clear, working code examples with brief explanations.'),

  /// Creative writing assistant
  creative(
      'You are a creative writing assistant. Be imaginative, vivid, and engaging.');

  /// The system prompt text for this preset
  final String prompt;

  const SystemPromptPreset(this.prompt);
}
